// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function CreateSession(arg1) {
  return window['go']['main']['App']['CreateSession'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function IsConnected() {
  return window['go']['main']['App']['IsConnected']();
}

export function KillPane(arg1) {
  return window['go']['main']['App']['KillPane'](arg1);
}

export function KillSession(arg1) {
  return window['go']['main']['App']['KillSession'](arg1);
}

export function KillWindow(arg1) {
  return window['go']['main']['App']['KillWindow'](arg1);
}

export function NewWindow(arg1) {
  return window['go']['main']['App']['NewWindow'](arg1);
}

export function PaneScrollback(arg1) {
  return window['go']['main']['App']['PaneScrollback'](arg1);
}

export function RenameSession(arg1, arg2) {
  return window['go']['main']['App']['RenameSession'](arg1, arg2);
}

export function RenameWindow(arg1, arg2) {
  return window['go']['main']['App']['RenameWindow'](arg1, arg2);
}

export function SelectPane(arg1) {
  return window['go']['main']['App']['SelectPane'](arg1);
}

export function SendKeys(arg1, arg2) {
  return window['go']['main']['App']['SendKeys'](arg1, arg2);
}

export function Sessions() {
  return window['go']['main']['App']['Sessions']();
}

export function SplitPane(arg1, arg2) {
  return window['go']['main']['App']['SplitPane'](arg1, arg2);
}
