// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function Connect(arg1:string):Promise<void>;

export function CreateSession(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function IsConnected():Promise<boolean>;

export function KillPane(arg1:string):Promise<void>;

export function KillSession(arg1:string):Promise<void>;

export function KillWindow(arg1:string):Promise<void>;

export function NewWindow(arg1:string):Promise<void>;

export function PaneScrollback(arg1:string):Promise<string>;

export function RenameSession(arg1:string,arg2:string):Promise<void>;

export function RenameWindow(arg1:string,arg2:string):Promise<void>;

export function SelectPane(arg1:string):Promise<void>;

export function SendKeys(arg1:string,arg2:string):Promise<void>;

export function Sessions():Promise<Array<domain.Session>>;

export function SplitPane(arg1:string,arg2:boolean):Promise<void>;
